Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace RestauranteEtec.Controllers
{
    [Authorize(Roles = "SuperAdmin, Admin")]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CargosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestauranteEtec.Data;
using RestauranteEtec.Models;

namespace RestauranteEtec.Controllers
{
    public class CargosController : Controller
    {
        private readonly Contexto _context;

        public CargosController(Contexto context)
        {
            _context = context;
        }

        // GET: Cargos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cargos.ToListAsync());
        }

        // GET: Cargos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cargo = await _context.Cargos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cargo == null)
            {
                return NotFound();
            }

            return View(cargo);
        }

        // GET: Cargos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cargos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Cargo cargo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cargo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cargo);
        }

        // GET: Cargos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cargo = await _context.Cargos.FindAsync(id);
            if (cargo == null)
            {
                return NotFound();
            }
            return View(cargo);
        }

        // POST: Cargos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Cargo cargo)
        {
            if (id != cargo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cargo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CargoExists(cargo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cargo);
        }

        // GET: Cargos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cargo = await _context.Cargos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cargo == null)
            {
                return NotFound();
            }

            return View(cargo);
        }

        // POST: Cargos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cargo = await _context.Cargos.FindAsync(id);
            _context.Cargos.Remove(cargo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CargoExists(int id)
        {
            return _context.Cargos.Any(e => e.Id == id);
        }
    }
}

Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestauranteEtec.Data;
using RestauranteEtec.Models;

namespace RestauranteEtec.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly Contexto _context;
        private readonly IWebHostEnvironment _webHost;

        public FuncionariosController(Contexto context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHost = webHostEnvironment;
        }

        // GET: Funcionarios
        public async Task<IActionResult> Index()
        {
            var contexto = _context.Funcionarios.Include(f => f.Cargo);
            return View(await contexto.ToListAsync());
        }

        // GET: Funcionarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionarios
                .Include(f => f.Cargo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (funcionario == null)
            {
                return NotFound();
            }
            ViewData["wwwroot"] = _webHost.WebRootPath;
            return View(funcionario);
        }

        // GET: Funcionarios/Create
        public IActionResult Create()
        {
            ViewData["CargoId"] = new SelectList(_context.Cargos, "Id", "Nome");
            return View();
        }

        // POST: Funcionarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Foto,Texto,CargoId,ExibirHome,OrdemExibicao")] 
            Funcionario funcionario, IFormFile Foto)
        {
            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    string pasta = Path.Combine(_webHost.WebRootPath, "images\\funcionarios");
                    var nomeArquivo = Guid.NewGuid().ToString() + "_" + Foto.FileName;
                    string caminhoArquivo = Path.Combine(pasta, nomeArquivo);
                    using (var stream = new FileStream(caminhoArquivo, FileMode.Create))
                    {
                        await Foto.CopyToAsync(stream);
                    };
                    funcionario.Foto = "images/funcionarios/" + nomeArquivo;
                }
                _context.Add(funcionario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CargoId"] = new SelectList(_context.Cargos, "Id", "Nome", funcionario.CargoId);
            return View(funcionario);
        }

        // GET: Funcionarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionarios.FindAsync(id);
            if (funcionario == null)
            {
                return NotFound();
            }
            ViewData["CargoId"] = new SelectList(_context.Cargos, "Id", "Nome", funcionario.CargoId);
            ViewData["wwwroot"] = _webHost.WebRootPath;
            return View(funcionario);
        }

        // POST: Funcionarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Foto,Texto,CargoId,ExibirHome,OrdemExibicao")]
            Funcionario funcionario, IFormFile NovaFoto)
        {
            if (id != funcionario.Id)
            {
                return NotFound();
            }
             

            if (ModelState.IsValid)
            {
                try
                {
                    if (NovaFoto != null)
                    {
                        string pasta = Path.Combine(_webHost.WebRootPath, "images\\funcionarios");
                        var nomeArquivo = Guid.NewGuid().ToString() + "_" + NovaFoto.FileName;
                        string caminhoArquivo = Path.Combine(pasta, nomeArquivo);
                        using (var stream = new FileStream(caminhoArquivo, FileMode.Create))
                        {
                            await NovaFoto.CopyToAsync(stream);
                        };
                        funcionario.Foto = "images/funcionarios/" + nomeArquivo;
                    }
                    _context.Update(funcionario);
                    await _context.SaveChangesAsync();
                }
 
                catch (DbUpdateConcurrencyException)
                {
                    if (!FuncionarioExists(funcionario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CargoId"] = new SelectList(_context.Cargos, "Id", "Nome", funcionario.CargoId);
            ViewData["wwwroot"] = _webHost.WebRootPath;
            return View(funcionario);
        }

        // GET: Funcionarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionarios
                .Include(f => f.Cargo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (funcionario == null)
            {
                return NotFound();
            }
            ViewData["wwwroot"] = _webHost.WebRootPath;
            return View(funcionario);
        }

        // POST: Funcionarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var funcionario = await _context.Funcionarios.FindAsync(id);
            _context.Funcionarios.Remove(funcionario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FuncionarioExists(int id)
        {
            return _context.Funcionarios.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SingInManager
@inject UserManager<ApplicationUser> UserManager
@{ 
    var user = await UserManager.GetUserAsync(User);
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>RestauranteEtec - @ViewData["Title"]</title>
    <!-- loader-->
    <link href="~/assets/css/pace.min.css" rel="stylesheet" />
    <script src="~/assets/js/pace.min.js"></script>
    <!--favicon-->
    <link rel="icon" href="~/assets/images/favicon.ico" type="image/x-icon">
    <!-- Vector CSS -->
    <link href="~/assets/plugins/vectormap/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- simplebar CSS-->
    <link href="~/assets/plugins/simplebar/css/simplebar.css" rel="stylesheet" />
    <!-- Bootstrap core CSS-->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <!-- animate CSS-->
    <link href="~/assets/css/animate.css" rel="stylesheet" type="text/css" />
    <!-- Icons CSS-->
    <link href="~/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <!-- Sidebar CSS-->
    <link href="~/assets/css/sidebar-menu.css" rel="stylesheet" />
    <!-- Custom Style-->
    <link href="~/assets/css/app-style.css" rel="stylesheet" />

</head>

<body class="bg-theme bg-theme2">

    <!-- Start wrapper-->
    <div id="wrapper">

        <!--Start sidebar-wrapper-->
        <div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
            <div class="brand-logo">
               <a asp-action="Index" asp-controller="Admin">
                   <h5 class="logo-text">Restaurante Etec</h5>
               </a>
            </div>
            <ul class="sidebar-menu do-nicescrol">
                <li>
                    <a asp-action="Index" asp-controller="Admin">
                        <i class="zmdi zmdi-view-dashboard"></i> <span>Dashboard</span>
                    </a>
                </li>

                <li class="sidebar-header text-info">SOCIAL</li>
                <li>
                    <a asp-action="Index" asp-controller="Blog">
                        <i class="zmdi zmdi-blogger"></i> <span>Blog</span>
                    </a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Contatos">
                        <i class="zmdi zmdi-email"></i> <span>Contatos</span>
                        <small class="badge float-right badge-light">Novo</small>
                    </a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Relatos">
                        <i class="zmdi zmdi-assignment"></i> <span>Relatos</span>
                    </a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Reservas">
                        <i class="zmdi zmdi-calendar-check"></i> <span>Reservas</span>
                        <small class="badge float-right badge-light">Novo</small>
                    </a>
                </li>

                <li class="sidebar-header text-success">MENU</li>
                <li>
                    <a asp-action="Index" asp-controller="Categorias">
                        <i class="zmdi zmdi-filter-list"></i> <span>Categorias</span>
                    </a>
                </li>

                <li>
                    <a asp-action="Index" asp-controller="Produtos">
                        <i class="zmdi zmdi-cutlery"></i> <span>Produtos</span>
                    </a>
                </li>

                <li class="sidebar-header text-danger">RECURSOS HUMANOS</li>
                <li>
                    <a asp-action="Index" asp-controller="Cargos">
                        <i class="zmdi zmdi-accounts-list"></i> <span>Cargos</span>
                    </a>
                </li>
                <li>
                    <a asp-action="Index" asp-controller="Funcionarios">
                        <i class="zmdi zmdi-account-circle"></i> <span>Funcionários</span>
                    </a>
                </li>
            </ul>
        </div>
            <!--End sidebar-wrapper-->
            <!--Start topbar header-->
            <header class="topbar-nav">
                <nav class="navbar navbar-expand fixed-top">
                    <ul class="navbar-nav mr-auto align-items-center">
                        <li class="nav-item">
                            <a class="nav-link toggle-menu" href="javascript:void();">
                                <i class="icon-menu menu-icon"></i>
                            </a>
                        </li>
                    </ul>

                    <ul class="navbar-nav align-items-centerright-nav-link">
                        <li class="nav-item dropdown-lg">
                            <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" href="javascript:void();">
                                <i class="fa fa-envelope-open-o"></i>
                            </a>
                        </li>
                        <li class="nav-item dropdown-lg">
                            <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" href="javascript:void();">
                                <i class="fa fa-bell-o"></i>
                            </a>
                        </li>
                       <li class="nav-item">
                           <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown" href="#">
                               <span class="user-profile">
                                   @if (user.ProfilePicture != null)
                                   {
                                       <img class="img-circle"
                                            src="data:image/*;base64,@(Convert.ToBase64String(user.ProfilePicture))"
                                            alt="Avatar do usuário">
                                   }
                                   else
                                   {
                                       <img src="https://via.placeholder.com/110x110" class="img-circle" alt="Avatar do usuário">
                                   }
                               </span>
                           </a>
                           <ul class="dropdown-menu dropdown-menu-right">
                               <li class="dropdown-item user-details">
                                   <a href="javaScript:void();">
                                       <div class="media">
                                           <div class="avatar">
                                               @if (UserManager.GetUserAsync(User).Result.ProfilePicture != null)
                                               {
                                                   <img class="align-self-start mr-3"
                                                        src="data:image/*;base64,@(Convert.ToBase64String(user.ProfilePicture))"
                                                        alt="Avatar do usuário">
                                               }
                                               else
                                               {
                                                   <img class="align-self-start mr-3" src="https://via.placeholder.com/110x110"
                                                        alt="Avatar do usuário">
                                               }
                                           </div>
                                           <div class="media-body">
                                               <h6 class="mt-2 user-title">@user.UserName</h6>
                                               <p class="user-subtitle">@user.NomeCompleto</p>
                                           </div>
                                       </div>
                                   </a>
                               </li>
                               <li class="dropdwn-divider"></li>
                               <li class="dropdown-item">
                                   <a asp-area="Identity" asp-page="/Account/Manage/Index">
                                       <i class="icon-wallet mr-2"></i> Perfil
                                   </a>
                               </li>
                               <li class="dropdown-divider"></li>
                               <li class="dropdown-item"><i class="icon-settings mr-2"></i> Configurações</li>
                               <li class="dropdown-divider"></li>
                               <li class="dropdown-item">
                                   <form id="formLogout" class="form-inline" asp-area="Identity" asp-page="/Account/Logout"
                                         asp-route-returnUrl="@Url.Action("Index", "Home", new { area = ""})">
                                       <a href="javascript:{}" onclick="document.getElementById('formLogout').submit(); return false;">
                                       <i class="icon-power mr-2"></i> Sair</a>
                                   </form>

                               </li>
                           </ul>
                       </li>
                    </ul>
                </nav>
            </header>
            <!--End topbar header-->

            <div class="clearfix"></div>

            <div class="content-wrapper">
                <div class="container-fluid">

                    @RenderBody()
                    <!--End Dashboard Content-->
                    <!--start overlay-->
                    <div class="overlay toggle-menu"></div>
                    <!--end overlay-->

                </div>
                <!-- End container-fluid-->

            </div><!--End content-wrapper-->
            <!--Start Back To Top Button-->
            <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
        <!--End Back To Top Button-->
        <!--Start footer-->
        <footer class="footer">
            <div class="container">
                <div class="text-center">
                    Copyright © @DateTime.Now.Year Restaurante Etec
                </div>
            </div>
        </footer>
        <!--End footer-->
        <!--start color switcher-->
        <div class="right-sidebar">
            <div class="switcher-icon">
                <i class="zmdi zmdi-settings zmdi-hc-spin"></i>
        </div>
        <div class="right-sidebar-content">

            <p class="mb-0">Gaussion Texture</p>
            <hr>

            <ul class="switcher">
                <li id="theme1"></li>
                <li id="theme2"></li>
                <li id="theme3"></li>
                <li id="theme4"></li>
                <li id="theme5"></li>
                <li id="theme6"></li>
            </ul>

            <p class="mb-0">Gradient Background</p>
            <hr>

            <ul class="switcher">
                <li id="theme7"></li>
                <li id="theme8"></li>
                <li id="theme9"></li>
                <li id="theme10"></li>
                <li id="theme11"></li>
                <li id="theme12"></li>
                <li id="theme13"></li>
                <li id="theme14"></li>
                <li id="theme15"></li>
            </ul>

        </div>
    </div>
    <!--end color switcher-->

    </div><!--End wrapper-->
    <!-- Bootstrap core JavaScript-->
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>

    <!-- simplebar js -->
    <script src="~/assets/plugins/simplebar/js/simplebar.js"></script>
    <!-- sidebar-menu js -->
    <script src="~/assets/js/sidebar-menu.js"></script>
    <!-- loader scripts -->
    <script src="~/assets/js/jquery.loading-indicator.js"></script>
    <!-- Custom scripts -->
    <script src="~/assets/js/app-script.js"></script>
    <!-- Chart js -->
    <script src="~/assets/plugins/Chart.js/Chart.min.js"></script>

    <!-- Index js -->
    <script src="~/assets/js/index.js"></script>
    @await RenderSectionAsync("Scripts", required: false) 

</body>
</html>